### PR TITLE
Fix version subcommands and generated output

### PR DESCRIPTION
**Pull request by mjura**
Fix version command and flag -o which shows
version output in following formats 'yaml', 'json'
and 'short'.

### CODE REVIEW

**Comment by ereslibre** [comment]
I agree with @MalloZup here, I don't think we need to print the version in different formats.

**Comment by mjura** [comment]
@ereslibre, @MalloZup ok, then let's clean wrong `version -output` command usage

**Comment by MalloZup** [comment]
@mjura https://github.com/kubic-project/dex-operator/blob/cf315a5e044bf200b87c2ac0774ea5f188e5530b/cmd/dex-operator/main.go#L102 backport to the dex-operator :sunflower:

**Comment by mjura** [comment]
@MalloZup thank you for merging and as follow up to this https://github.com/kubic-project/dex-operator/pull/28

**Pull request merged**
