### PR TITLE
Add unittest to registries-operator

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by mjura** [comment]
This depends on https://github.com/kubic-project/registries-operator/pull/34

**Comment by pablochacin** [comment]
Issues from review addressed in last commit. Ready for review.

**Comment by Klaven** [comment]
I suggest we close this PR due to the work done in https://github.com/kubic-project/registries-operator/pull/41 and https://github.com/kubic-project/registries-operator/pull/35

**Comment by mjura** [comment]
> I suggest we close this PR due to the work done in #41 and #35

I agree with Marek

**Pull request closed without merging**
