### PR TITLE
Document PSP Requirements for local run

### PR DESCRIPTION
**Pull request by pablochacin**
Document PSP requirements for running operator locally.

### CODE REVIEW

**Comment by MalloZup** [comment]
Check out rhe red

**Comment by pablochacin** [comment]
This PR is based on PR #13  as it is an addendum.

**Comment by MalloZup** [comment]
Lgtm but we need to fix later the red

**Comment by ereslibre** [comment]
This PR has conflicts now after https://github.com/kubic-project/registries-operator/pull/13 was merged; it needs a rebase on top of master (and probably dropping commit `0d769f5817d7d89d0634a56027f525285464fedc`)

**Comment by MalloZup** [comment]
(confiltcts solved, merged thx)

**Pull request merged**
