### PR TITLE
Move to leap15.0 docker image

### PR DESCRIPTION
**Pull request by MalloZup**
# Description:

as discussed we move to leap15

### CODE REVIEW

**Comment by ereslibre** [comment]
CI is failing because it cannot find `go1.11`

**Comment by MalloZup** [comment]
burriot

**Comment by mjura** [comment]
@MalloZup: can you please add more info why do we want to move to Leap 15.0?

**Comment by MalloZup** [comment]
@mjura  we want to reduce the number of chaning things and failure we have on building img, at least for dockerHug and ci ( not kiwi)

On the opposite, the contra question in this case is , do we have a need to stay for the `operators` (only) to TW?

**Comment by MalloZup** [comment]
@mjura thank you for your question. 

For kubic-init project we need to stay on TW becasue we need the latest kubernetes pkg

**Pull request merged**
